Change an HTML id used twice into a class
Sometimes when I run crates.io locally, and I'm signed in, I get this
error in the js console:

```
Error: Assertion Failed: Attempted to register a view with an id already
in use: current-user-links
```

Id isn't required for rl-dropdowns, so I changed current-user-links to
be a class instead.