tests/server_binary: Use `unwrap()` to fail test instead of returning error
Returning an `Err` causes the following unhelpful output:

```
thread 'server_binary::startup_without_database' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/test/src/lib.rs:184:5
```