Add test for DOS proof-of-concept
The test boots a test server and then sends a request the equivalent of:

`curl -v -X PUT "http://127.0.0.1:12345/" --data `python3 -c "import sys; sys.stdout.write('a'*10000)"` -H "Content-Length: 11111111111111111111"`

When run as `cargo +stable test content_length`, the test process will
abort after printing "memory allocation of 11111111111111111111 bytes
failed".

When run with `+beta` or `+nightly` the standard library is built with
debug assertions so the test suite does not abort and the test fails
with:

```
thread 'tests::content_length_too_large' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tests::content_length_too_large' panicked at 'should be a valid response: hyper::Error(IncompleteMessage)', src/tests.rs:205:10
```